# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '自定义cell编辑状态' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'

end
