# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '滚动轮播图(上下+左右)' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Masonry'

end
